### PR TITLE
Split YAML file

### PR DESCRIPTION
**Pull request by alex-seville**
It's super annoying to have a huge YAML file, and it's only going to get worse.

This PR puts partial YAML files into a `schema` subdir and then $ref them into an index YAML file.

Definitions, Paths, and Info are broken out.

The build script is update to use bundle which also converts to json (eliminating the js-yaml dep).

I also store the generated json file into a `dist` directory, making it clear what is the source and what is the built distributable (it's not super clear right now).

### CODE REVIEW

**Comment by jeremyruppel** [comment]
So much 👍

**Comment by superic** [comment]
👍 💃

**Comment by alex-seville** [comment]
Okay, I think this is good to merge once the sdk repo has been corrected.  In any case, 1.0.0 is what is being used in prod by people AFAIK.

**Comment by jeremyruppel** [comment]
So much 👍

**Pull request merged**
